### PR TITLE
requires is not needed

### PR DESCRIPTION
**Pull request by paul-szczepanek-arm**

### CODE REVIEW

**Comment by AGlass0fMilk** [comment]
Is this true for the new tools?

What about in baremetal mode? Perhaps it should be mentioned if you must do this in baremetal mode.

**Comment by paul-szczepanek-arm** [comment]
The new tools ignores it, the old tools ignores it (which was a surprise to me). We don't support baremetal yet.

**Comment by pan-** [comment]
> We don't support baremetal yet.
I'm certain Bluetooth supports baremetal. 

Maybe you can just indicates the require step is for baremetal applications.

**Comment by paul-szczepanek-arm** [comment]
OK, in which case it's a different kind of requires, let me fix that.

**Review by pan- — APPROVED** [review]

**Pull request merged**
